version: "3.8"

services:
  postgres_gwi:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gwi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: favorites
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
