version: '3.8'

services:
  api:
    build: .
    image: gwi-favorites-api:latest
    container_name: gwi-favorites-api
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=dev #to seed dummy data