definitions:
  handlers.EditDescriptionRequest:
    properties:
      description:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  utils.SuccessResponse:
    properties:
      data: {}
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/users/{userID}/favorites:
    get:
      description: Get all favorite assets (charts, insights, audiences) for the specified
        user.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "401":
          description: Unauthorized - missing or invalid token
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: List all favorites for a user
      tags:
      - favorites
    post:
      description: Add a new favorite asset for the user (chart, insight, or audience).
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Asset to add
        in: body
        name: asset
        required: true
        schema: {}
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Add a favorite asset
      tags:
      - favorites
  /v1/users/{userID}/favorites/{assetID}:
    delete:
      description: Remove an asset from the user's favorites by asset external ID
        and type.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Asset External ID
        in: path
        name: assetID
        required: true
        type: string
      - description: Asset Type (chart, insight, audience)
        in: query
        name: type
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Remove a favorite asset
      tags:
      - favorites
    patch:
      description: Edit the description of a favorite asset.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      - description: Asset External ID
        in: path
        name: assetID
        required: true
        type: string
      - description: Asset Type (chart, insight, audience)
        in: query
        name: type
        required: true
        type: string
      - description: New Description
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.EditDescriptionRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Edit favorite asset description
      tags:
      - favorites
swagger: "2.0"
